from datetime import datetime
from collections import defaultdict
from contextlib import suppress

from bbot.modules.output.base import BaseOutputModule


SEVERITY_ORDER = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4, "unknown": 5}

SEVERITY_COLORS = {
    "critical": "#c0392b",
    "high":     "#e67e22",
    "medium":   "#f1c40f",
    "low":      "#27ae60",
    "info":     "#2980b9",
    "unknown":  "#7f8c8d",
}

SEVERITY_BG = {
    "critical": "#fde8e8",
    "high":     "#fef0e6",
    "medium":   "#fefde6",
    "low":      "#e8f8ee",
    "info":     "#e6f2fb",
    "unknown":  "#f0f0f0",
}


def _sev(finding: dict) -> str:
    return finding.get("severity", "unknown").lower()


def _sort_findings(findings: list) -> list:
    return sorted(findings, key=lambda f: SEVERITY_ORDER.get(_sev(f), 5))


HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Consulting Recon Report — {target}</title>
<style>
  *, *::before, *::after {{ box-sizing: border-box; }}
  body {{ font-family: 'Segoe UI', Arial, sans-serif; background: #f4f6f9; color: #2c3e50; margin: 0; padding: 0; }}
  header {{ background: #1a252f; color: #fff; padding: 24px 40px; }}
  header h1 {{ margin: 0; font-size: 1.6rem; }}
  header .meta {{ font-size: 0.85rem; color: #95a5a6; margin-top: 6px; }}
  .container {{ max-width: 1200px; margin: 0 auto; padding: 30px 40px; }}
  .summary-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(130px, 1fr)); gap: 16px; margin-bottom: 32px; }}
  .summary-card {{ border-radius: 8px; padding: 16px; text-align: center; background: #fff; border-top: 4px solid {sev_color}; box-shadow: 0 2px 6px rgba(0,0,0,0.07); }}
  .summary-card .count {{ font-size: 2rem; font-weight: 700; }}
  .summary-card .label {{ font-size: 0.8rem; color: #7f8c8d; text-transform: uppercase; letter-spacing: 0.5px; margin-top: 4px; }}
  .section {{ margin-bottom: 36px; }}
  .section h2 {{ font-size: 1.15rem; border-bottom: 2px solid #dde; padding-bottom: 6px; margin-bottom: 16px; color: #1a252f; }}
  .finding {{ border-radius: 6px; margin-bottom: 12px; overflow: hidden; box-shadow: 0 1px 4px rgba(0,0,0,0.06); }}
  .finding-header {{ display: flex; align-items: center; gap: 10px; padding: 12px 16px; cursor: pointer; background: #fff; border-left: 5px solid {sev_color}; }}
  .finding-header .badge {{ border-radius: 4px; padding: 2px 8px; font-size: 0.72rem; font-weight: 700; text-transform: uppercase; letter-spacing: 0.5px; color: #fff; flex-shrink: 0; }}
  .finding-header .title {{ flex: 1; font-size: 0.92rem; font-weight: 600; }}
  .finding-header .source-tag {{ font-size: 0.72rem; color: #7f8c8d; border: 1px solid #ccc; border-radius: 10px; padding: 1px 8px; flex-shrink: 0; }}
  .finding-body {{ background: {sev_bg}; padding: 14px 16px; font-size: 0.85rem; line-height: 1.6; display: none; }}
  .finding-body.open {{ display: block; }}
  .finding-body table {{ border-collapse: collapse; width: 100%; }}
  .finding-body td {{ padding: 4px 8px; vertical-align: top; }}
  .finding-body td:first-child {{ font-weight: 600; white-space: nowrap; color: #555; width: 110px; }}
  .finding-body code {{ background: rgba(0,0,0,0.05); border-radius: 3px; padding: 1px 5px; font-size: 0.82rem; word-break: break-all; }}
  .empty {{ color: #95a5a6; font-style: italic; padding: 12px; }}
  .toc {{ background: #fff; border-radius: 8px; padding: 16px 20px; margin-bottom: 28px; box-shadow: 0 1px 4px rgba(0,0,0,0.06); }}
  .toc h2 {{ margin: 0 0 10px; font-size: 1rem; color: #555; }}
  .toc a {{ display: inline-block; margin: 3px 6px 3px 0; padding: 3px 10px; border-radius: 12px; font-size: 0.8rem; background: #ecf0f1; color: #2c3e50; text-decoration: none; }}
  .toc a:hover {{ background: #d5dbdb; }}
  footer {{ text-align: center; color: #95a5a6; font-size: 0.78rem; padding: 20px; }}
</style>
<script>
  document.addEventListener('DOMContentLoaded', function() {{
    document.querySelectorAll('.finding-header').forEach(function(hdr) {{
      hdr.addEventListener('click', function() {{
        var body = hdr.nextElementSibling;
        body.classList.toggle('open');
      }});
      // Auto-expand critical / high
      if (hdr.querySelector('.badge') && ['CRITICAL','HIGH'].includes(hdr.querySelector('.badge').textContent)) {{
        hdr.nextElementSibling.classList.add('open');
      }}
    }});
  }});
</script>
</head>
<body>
<header>
  <h1>Consulting Recon Report</h1>
  <div class="meta">Target: <strong>{target}</strong> &nbsp;|&nbsp; {scan_date} &nbsp;|&nbsp; SuizerAudit</div>
</header>
<div class="container">

{summary_html}

<div class="toc">
  <h2>Sections</h2>
  {toc_html}
</div>

{sections_html}

</div>
<footer>Generated by SuizerAudit — For authorized use only.</footer>
</body>
</html>
"""

SUMMARY_CARD = """
<div class="summary-card" style="border-top-color:{color}">
  <div class="count" style="color:{color}">{count}</div>
  <div class="label">{label}</div>
</div>"""

FINDING_BLOCK = """
<div class="finding">
  <div class="finding-header" style="border-left-color:{color}">
    <span class="badge" style="background:{color}">{severity}</span>
    <span class="title">{title}</span>
    <span class="source-tag">{source}</span>
  </div>
  <div class="finding-body" style="background:{bg}">
    <table>{rows}</table>
  </div>
</div>"""


def _badge_color(sev: str) -> str:
    return SEVERITY_COLORS.get(sev, SEVERITY_COLORS["unknown"])


def _bg_color(sev: str) -> str:
    return SEVERITY_BG.get(sev, SEVERITY_BG["unknown"])


def _row(label: str, value: str) -> str:
    if not value:
        return ""
    return f"<tr><td>{label}</td><td><code>{value}</code></td></tr>"


def _render_finding(f: dict, source: str) -> str:
    sev = _sev(f)
    color = _badge_color(sev)
    bg = _bg_color(sev)
    title = f.get("title") or f.get("description", "Finding")[:120]
    rows = (
        _row("URL", f.get("url", ""))
        + _row("Endpoint", f.get("endpoint", ""))
        + _row("Type", f.get("type", ""))
        + _row("Description", f.get("description", ""))
        + _row("Evidence", (f.get("evidence") or f.get("match") or "")[:400])
        + _row("Context", (f.get("context") or f.get("recommendation") or "")[:400])
    )
    return FINDING_BLOCK.format(
        color=color, bg=bg, severity=sev.upper(),
        title=title, source=source, rows=rows
    )


def _section(section_id: str, heading: str, findings: list, source_tag: str) -> str:
    if not findings:
        content = '<p class="empty">No findings in this category.</p>'
    else:
        content = "\n".join(_render_finding(f, source_tag) for f in _sort_findings(findings))
    return f'<div class="section" id="{section_id}"><h2>{heading}</h2>{content}</div>'


class consulting_report(BaseOutputModule):
    watched_events = ["FINDING", "TECHNOLOGY", "VULNERABILITY"]
    meta = {
        "description": "Generate a unified HTML consulting report from BBOT, JsFuzzer, and MendixRecon findings",
        "created_date": "2024-01-01",
        "author": "@consulting",
    }
    options = {"output_file": ""}
    options_desc = {"output_file": "HTML report output path (default: <scan_dir>/CONSULTING_REPORT.html)"}

    output_filename = "CONSULTING_REPORT.html"

    async def setup(self):
        self._prep_output_dir(self.output_filename)
        self._findings = defaultdict(list)
        self._technologies = set()
        self._target = str(self.scan.target)
        return True

    async def handle_event(self, event):
        if event.type == "TECHNOLOGY":
            data = event.data
            if isinstance(data, dict):
                self._technologies.add(data.get("technology", ""))
            return

        tags = set(getattr(event, "tags", []) or [])
        data = event.data

        if not isinstance(data, dict):
            return

        finding = {
            "severity": "info",
            "title": "",
            "url": "",
            "endpoint": "",
            "type": event.type,
            "description": data.get("description", ""),
            "evidence": "",
            "context": "",
            "recommendation": "",
        }

        if event.type == "VULNERABILITY":
            finding["severity"] = data.get("severity", "medium").lower()
            finding["title"] = data.get("name", data.get("description", "Vulnerability"))[:200]
            finding["url"] = data.get("url", "")
        else:
            finding["title"] = data.get("description", "Finding")[:200]
            finding["url"] = data.get("url", "")

        # Classify by source based on tags
        if "jsfuzzer" in tags:
            bucket = "jsfuzzer"
        elif "mendix-recon" in tags:
            bucket = "mendix"
        else:
            bucket = "bbot"

        # Extract severity from tags if not in data
        for tag in tags:
            if tag.startswith("severity-"):
                finding["severity"] = tag.split("severity-", 1)[1]
                break

        self._findings[bucket].append(finding)

    async def report(self):
        all_findings = (
            self._findings["bbot"]
            + self._findings["jsfuzzer"]
            + self._findings["mendix"]
        )

        # Count by severity across all buckets
        counts = defaultdict(int)
        for f in all_findings:
            counts[_sev(f)] += 1

        # Summary cards
        summary_cards = "\n".join(
            SUMMARY_CARD.format(
                color=_badge_color(sev),
                count=counts.get(sev, 0),
                label=sev.capitalize(),
            )
            for sev in ["critical", "high", "medium", "low", "info"]
        )
        summary_cards += SUMMARY_CARD.format(
            color="#7f8c8d",
            count=len(self._technologies),
            label="Technologies",
        )
        summary_html = f'<div class="summary-grid">{summary_cards}</div>'

        # TOC
        sections = [
            ("bbot-findings", "BBOT Native Findings"),
            ("js-findings", "JavaScript Analysis (JsFuzzer)"),
            ("mendix-findings", "Mendix Audit (MendixRecon)"),
        ]
        toc_html = " ".join(f'<a href="#{sid}">{name}</a>' for sid, name in sections)

        # Sections
        sections_html = "\n".join([
            _section("bbot-findings", "BBOT Native Findings", self._findings["bbot"], "bbot"),
            _section("js-findings", "JavaScript Analysis (JsFuzzer)", self._findings["jsfuzzer"], "jsfuzzer"),
            _section("mendix-findings", "Mendix Audit (MendixRecon)", self._findings["mendix"], "mendix-recon"),
        ])

        html = HTML_TEMPLATE.format(
            target=self._target,
            scan_date=datetime.now().strftime("%Y-%m-%d %H:%M UTC"),
            sev_color=_badge_color("critical"),
            sev_bg=_bg_color("info"),
            summary_html=summary_html,
            toc_html=toc_html,
            sections_html=sections_html,
        )

        with suppress(Exception):
            self.output_file.write_text(html, encoding="utf-8")
            self.info(f"Consulting report saved to {self.output_file}")

    async def cleanup(self):
        with suppress(Exception):
            if getattr(self, "_file", None) is not None:
                self._file.close()
